### ISSUE TITLE
install_NFC.sh should copy android.hardware.nfc.hcef.xml

### ISSUE THREAD

**Issue by wintonliuwen** [NXPNFCLinux/nxpnfc_android_marshmallow#1]
install_NFC.sh should also copy android.hardware.nfc.hcef.xml to frameworks/native/data/etc/android.hardware.nfc.hcef.xml , right?

**Comment by jgeslin** [comment]
This is useless if you follow instructions detailed in chapter §3.1.4 of [AN11690](https://github.com/NXPNFCLinux/nxpnfc_android_marshmallow/blob/master/AN11690%20-%20NXPNCI%20Android%20Porting%20Guidelines.pdf). There the android.hardware.nfc.hcef.xml is added to the build directly from NxpNfcAndroid folder.
