### ISSUE TITLE
NFC shut down is initiated after ~12 sec, of initalization

### ISSUE THREAD

**Issue by Sourabh-Pandit** [NXPNFCLinux/nxpnfc_android_marshmallow#3]
I have followed the porting guide mentioned for Pn7150, and ported the Marshmallow stack for our system.
As per the porting guide, all the component are used have tag "NFC_NCIHALx_AR3C.4.5.0_M_OpnSrc".

But it is seen that once the stack is initialized, it starts the shutdown the NFC after 12-15 sec..

From the logs it is clear that, when NFCC is getting correctly configured for (polling/listening) and is in RFST_DISCOVERY state. And after around 12 sec, NFC stack start the shut down procedure.

After debugging, it is found that the TML code of Marshmallow is the one, because of which the Stack is shut down...

NXP stack(TML:- Android Marshmallow) uses select and read system call combination to read the data from NFCC over I2C,  select system call tells whether there is any data to read on i2c. Select call  function shall block until  there is any data to be read on i2c or until the timeout occurs. 

In the TML , timeout for select is set to 2 sec. After the timeout, TML logic retries again to read NFCC over i2c, using select and read system call combination again for MAX_READ_RETRY_COUNT( #defined to 5). And after that NFC shut down is initiated, if 

Again it is observed that the TML code of 'Lollipop', implemented the reading logic bit differently, it simply ignores the read errors, and keeps the read pending always..

As of now after replacing /external/libnfc-nci/halimpl/pn54x/tml/phTmlNfc.c of lollipop version, the stack is running good. No shutdown is seen.

But I have couple of doubts:-

1)	What is the expected behavior from NFC controller, once it is configured for Polling-Listening cycle, ie configured for DISCOVERY(RF_DISCOVER_CMD).
2)	Why I2C read logic is implemented to return NFCSTATUS_READ_FAILED, after MAX_READ_RETRY_COUNT iteration, In Android M and later. In Android Lollipop, the read errors were ignored.

**Comment by jgeslin** [comment]
Hi,

1. When in Discovery mode, the NFC Controller autonomously and continuously sense for remote NFC devices (tag, P2P device or reader according to the configuration). When found, it reports to the application processor (through I2C) the discovery information.

2. It looks to me that there is an issue at the low level module level. Indeed, the provided pn5xx_i2c kernel module code doesn't implements "poll" methods which should lead to have the select call returning without any error (and indicating both read and write operation and possible without any restriction) so should never fall on timeout.

Are you loading the /dev/pn544 device node based on provide pn5xx_i2c kernel driver provided ?

Regards,
Jeremy.

**Comment by Sourabh-Pandit** [comment]
Thanks Jeremy for your reply. 
But as I said, if we replace the TML of Marshmallow with that of Lollipop( keeping rest of the stack of Marshmallow), it works fine. Still you believe it's a low level issue ?

**Comment by jgeslin** [comment]
Hi,

The update done in Mashmallow was to improve stability (avoiding deadlock encountered by some customer in bad conditions) but is considering stable low level driver. 
However, if you are fine with the lollipop TML version you can leave with it.

Regards,
Jeremy.

**Comment by Sourabh-Pandit** [comment]
Ok, I think we are good with the TML version of lollipop as of now... 
Thanks again.
