### ISSUE TITLE
NFC  cannot be enabled

### ISSUE THREAD

**Issue by njitwb** [NXPNFCLinux/nxpnfc_android_marshmallow#4]
Hi, 

Our NFC chip is PN7150, and we observed that several boards that had been able to work properly were suddenly unable to enable NFC. I found that it will at the wrong response status "STATUS_INVALID_PARAM". Below is the log when performing RF Settings BLK 1:

01-01 00:01:30.656  1201  1403 D NxpHal  : Performing RF Settings BLK 1
01-01 00:01:30.659  1201  1403 D NxpExtns: const nxp::CNfcParam* nxp::CNfcConfig::find(const char*) const found NXP_RF_CONF_BLK_1= ??5???D?
01-01 00:01:30.670  1201  1410 D NxpTml  : PN54X - Write requested.....
01-01 00:01:30.670  1201  1410 D NxpTml  : PN54X - Invoking I2C Write.....
01-01 00:01:30.675  1201  1410 D NxpNciX : len = 166 > 2002A313A00D0604359001F401A00D06064401900300A00D060630B0011000A00D0606420200FFFFA00D03063F04A00D0620428800FFFFA00D0422442300A00D06222D50340C00A00D063242F800FFFFA00D06342D24370C00A00D06343386800070A00D0434442200A00D06422D15450D00A00D0446442200A00D06462D05590E00A00D0644428800FFFFA00D06562D059F0C00A00D0654428800FFFFA00D060A3380860070
01-01 00:01:30.676  1201  1410 D NxpTml  : PN54X - I2C Write successful.....
01-01 00:01:30.676  1201  1410 D NxpTml  : PN54X - Posting Fresh Write message.....
01-01 00:01:30.676  1201  1410 D NxpTml  : PN54X - Tml Writer Thread Running................
01-01 00:01:30.676  1201  1412 D NxpHal  : write successful status = 0x0
01-01 00:01:30.676  1201  1403 D NxpHal  : Response timer started
01-01 00:01:30.676  1201  1403 D NxpHal  : Waiting after ext cmd sent
01-01 00:01:30.695  1201  1409 D NxpTml  : PN54X - I2C Read successful.....
01-01 00:01:30.695  1201  1409 D NxpNciR : len =  29 > 40021A090CA00DA00DA00DA00DA00DA00DA00DA00DA00DA00DA00DA00D
01-01 00:01:30.695  1201  1409 D NxpTml  : PN54X - Posting read message.....
01-01 00:01:30.695  1201  1412 D NxpHal  : read successful status = 0x0
01-01 00:01:30.695  1201  1412 D NxpHal  : phNxpNciHal_print_res_status: response status =STATUS_INVALID_PARAM
01-01 00:01:30.696  1201  1409 D NxpTml  : PN54X - Read requested.....
01-01 00:01:30.696  1201  1403 D NxpHal  : Response timer stopped
01-01 00:01:30.696  1201  1409 D NxpTml  : PN54X - Invoking I2C Read.....
01-01 00:01:30.696  1201  1403 D NxpHal  : Checking response
01-01 00:01:30.696  1201  1403 D NxpFwDnld: phDnldNfc_LoadRecoveryFW /system/vendor/firmware/libpn548ad_fw.so 
01-01 00:01:30.696  1201  1403 E NxpFwDnld: NULL handler : unable to load the library file, specify correct path
01-01 00:01:30.696  1201  1403 D NxpFwDnld: FW Image Length - ImageInfoLen 0
01-01 00:01:30.696  1201  1403 D NxpFwDnld: FW Image Info Pointer - pImageInfo 0x0
01-01 00:01:30.696  1201  1403 E NxpFwDnld: Image extraction Failed - invalid imginfo or imginfolen!!
01-01 00:01:30.696  1201  1403 E NxpFwDnld: Error loading libpn54x_fw !!

If I can confirm that this is not caused by I2C transmission, what else will cause this problem?

**Comment by jgeslin** [comment]
Hi,

It sounds to be due to corrupted RF settings in PN7150 EEPROM.
We just discover that it may happen in some rare conditions (voltage) on some ICs.
We provided a [new libnfc-nxp.conf file](https://github.com/NXPNFCLinux/nxpnfc_android_marshmallow/blob/master/conf/PN7150/libnfc-nxp.conf) to prevent such issue.
To workaround the issue with corrupted ICs please try out attached patch
[patch_RfSettingInvalidParam.txt](https://github.com/NXPNFCLinux/nxpnfc_android_marshmallow/files/1230791/patch_RfSettingInvalidParam.txt) to be applied in external/libnfc-nci folder:

`$ cd $ANDROID_BUILD_TOP/external/libnfc-nci`
`$ patch -p1 <patch_RfSettingInvalidParam.txt`

Regards,
Jeremy.

**Comment by njitwb** [comment]
It works, thank you. By the way, does the rare conditions(voltage) means ESD? Because we use the external RF antenna, so the testers may be touch it. And the ESD entry the PN7150.

**Comment by njitwb** [comment]
Also, would you please explain what the new config has changed? 

@@ -75,11 +75,9 @@ NXP_EXT_TVDD_CFG_2={20, 02, 07, 01, A0, 0E, 03, 06, 64, 00}
 ###############################################################################
 # NXP Proprietary core configuration extensions
 # For more details refer to the NFC Controller User Manual
-NXP_CORE_CONF_EXTN={20, 02, 24, 04,
+NXP_CORE_CONF_EXTN={20, 02, 09, 02,
     A0, 5E, 01, 01,
-    A0, 40, 01, 00,
-    A0, 0D, 04, 34, 44, 22, 00,
-    A0, 1D, 11, 57, 33, 14, 17, 00, AA, 85, 00, 80, 55, 2A, 04, 00, 63, 00, 00, 00
+    A0, 40, 01, 00
 }
 
 ###############################################################################
@@ -114,7 +112,7 @@ NXP_RF_CONF_BLK_1={ 20, 02, A3, 13,
     A0, 0D, 06, 06, 42, 02, 00, FF, FF,
     A0, 0D, 03, 06, 3F, 04,
     A0, 0D, 06, 20, 42, 88, 00, FF, FF,
-    A0, 0D, 04, 22, 44, 23, 00,
+    A0, 0D, 04, 22, 44, 22, 00,
     A0, 0D, 06, 22, 2D, 50, 34, 0C, 00,
     A0, 0D, 06, 32, 42, F8, 00, FF, FF,
     A0, 0D, 06, 34, 2D, 24, 37, 0C, 00,
@@ -128,3 +126,7 @@ NXP_RF_CONF_BLK_1={ 20, 02, A3, 13,
     A0, 0D, 06, 54, 42, 88, 00, FF, FF,
     A0, 0D, 06, 0A, 33, 80, 86, 00, 70
 }
+
+NXP_RF_CONF_BLK_2={ 20, 02, 15, 01,
+    A0, 1D, 11, 57, 33, 14, 17, 00, AA, 85, 00, 80, 55, 2A, 04, 00, 63, 00, 00, 00
+}

**Comment by jgeslin** [comment]
The conditions in which it could happen are not related to ESD but rather to voltage drop during the EEPROM access.
Regarding the new config, there is basically no change meaning all settings are applied the same. Only the order and the split into different NCI commands to access different EEPROM setting was updated.

**Comment by njitwb** [comment]
Got it. Thanks a lot.
