### ISSUE TITLE
Cannot recognize the card when put the card near the antenna in advance.

### ISSUE THREAD

**Issue by njitwb** [NXPNFCLinux/nxpnfc_android_marshmallow#6]
Hi,
  In our project, the default is HCE mode. After user presses the NFC button, the NFC will change to Reader mode. In Reader mode, the APP will connect to NFC and read the data.

  Now we met a problem. If we put a NFC card nearby then press the NFC button to change to Reader mode, this time the board cannot recognize the card. We have to move NFC card away then back to antenna, then board can recognize the card.

  How can we fix this problem?

**Comment by jgeslin** [comment]
Hi,

May you please indicates how you switch from HCE to Reader Mode ?
Which API are you calling from the application ?

Regards,
Jeremy.

**Comment by njitwb** [comment]
@jgeslin 
We use following API to enable Reader mode
nfcAdapter.enableForegroundDispatch()

**Comment by jgeslin** [comment]
enableForegroundDispatch does not "enable" reader mode. It only gives the priority of the tag dispatch to your application.
Usually NFC service is set to act as HCE and Reader modes at the same time (in addition to P2P). There should not need any user action to enable Reader mode.

**Comment by njitwb** [comment]
@jgeslin 

I know that, HCE and Reader modes work at the same time. But we want the NFC read the data only when the NFC button(a general button) is on pressed. You can interpret Reader Mode as a function of NFC to read data. 

But there's a problem when I've got my card near the antenna when I don't have enable dispatch. After that, I pressed the NFC button and enable dispatch, but APP didn't recognize the card. The card can only be identified if it is re close to the antenna.

What advice do you have for solving this problem? Or is there any other API that can be called to let NFC to re - report events?.

**Comment by jgeslin** [comment]
You may give a try calling enableReaderMode then disabledReaderMode when pressing the button.
Otherwise another workaround can be to simple restart the NFC service (simply kill it, android will restart it automatically).

**Comment by njitwb** [comment]
@jgeslin 
we tried with enableReaderMode and disabledReaderMode can get tag with onTagDiscovered(Tag tag) in callback, but there is no Ndef messages in the TAG, we tried to search mTechStringList of the TAG, find no Ndef, So we can't use Ndef.get(Tag tag) to get the Ndef message;
by using nfcAdapter.enableForegroundDispatch(), we can get Ndef message and TAG from intent:
Parcelable[] ndefMsg = intent.getParcelableArrayExtra(NfcAdapter.EXTRA_NDEF_MESSAGES);
Tag tag = intent.getParcelableExtra(NfcAdapter.EXTRA_TAG);

so, Is there any way to get Ndef message with enableReaderMode and disabledReaderMode? Thanks!

**Comment by njitwb** [comment]
@jgeslin 
We find the way to get Ndef message with enableReaderMode and disabledReaderMode.
we use Ndef ndef = Ndef.get(tag); to get Ndef onTagDiscovered callback, and use NdefMessage msg = ndef.getNdefMessage(); to get the ndef messages. Thanks!
