### ISSUE TITLE
I2C fragmentation implemented on PN7150

### ISSUE THREAD

**Issue by Danielchiu73** [NXPNFCLinux/nxpnfc_android_marshmallow#8]
Hi,

We get "STATUS_SYNTAX_ERROR" status code during PN7150 initialization(Core and RF configuration settings) duo to DH I2C transport buffer limitation(32 byte).

We wants to implement the PN7150 I2C transport fragmentation to avoid the  "STATUS_SYNTAX_ERROR" status code by setting NXP_I2C_FRAGMENTATION_ENABLED=0x01 in the libnfc-nxp.conf. but it does not work.

Do we need to do other setting? Thanks.

Below is the ADB log for reference:
01-01 23:40:49.717  1022  1232 D NxpNciX : SEND len =  46 > 20022B0D2801002101003001083101033304010203045401065001025B010060010E80010181010182010E180101**
01-01 23:40:49.717  1022  1232 D NxpTml  : PN54X - I2C Write successful.....
01-01 23:40:49.717  1022  1232 D NxpTml  : PN54X - Posting Fresh Write message.....
01-01 23:40:49.717  1022  1234 D NxpHal  :  --- client_thread msg 785 entry ...
01-01 23:40:49.717  1022  1234 D NxpHal  : write successful status = 0x0
01-01 23:40:49.717  1022  1234 D NxpHal  :  >>> client_thread msg 785 exit ...
01-01 23:40:49.717  1022  1232 D NxpTml  : PN54X - Tml Writer Thread Running................
01-01 23:40:49.717  1022  1218 D NxpHal  : Response timer started
01-01 23:40:49.717  1022  1218 D NxpHal  : Waiting after ext cmd sent
01-01 23:40:49.726   649  1074 D TelephonyRegistry: listen oscl: hasNotifySubscriptionInfoChangedOccurred==false no callback
01-01 23:40:49.732  1022  1231 D NxpTml  : PN54X - I2C Read successful.....
01-01 23:40:49.732  1022  1231 D NxpNciR : RECV len =   4 > 40020105
01-01 23:40:49.732  1022  1231 D NxpTml  : PN54X - Posting read message.....
01-01 23:40:49.732  1022  1234 D NxpHal  :  --- client_thread msg 785 entry ...
01-01 23:40:49.732  1022  1234 D NxpHal  : read successful status = 0x0
01-01 23:40:49.732  1022  1234 D NxpHal  : phNxpNciHal_print_res_status: response status =STATUS_SYNTAX_ERROR
01-01 23:40:49.732  1022  1234 W NxpHal  : Invalid Data from config file . Aborting.

Regards.
Daniel

**Comment by jgeslin** [comment]
Indeed, in current R1.2 release the fragmentation mechanism allowing limiting I2C transfer size is partially removed. 
Please find attached patch adding the support: [patch_I2cFragmentation.txt](https://github.com/NXPNFCLinux/nxpnfc_android_marshmallow/files/1475026/patch_I2cFragmentation.txt)

Then, to make use of it:
- NXP_I2C_FRAGMENTATION_ENABLED must be set to 0x01 in /etc/libnfc-nxp.conf file
- PHNFC_I2C_FRAGMENT_SIZE, in external\libnfc-nci\halimpl\pn54x\common\phNfcStatus.h file, must be defined to the max I2C transfer size (for instance 32 bytes in your case)

**Comment by Danielchiu73** [comment]
Hi,
Thanks a lot for your support. customer can implement the I2C Fragmentation function.

But now customer get  "STATUS_INVALID_PARAM" error during NXP_RF_CONF_BLK_1 setting(RF_TRANSITION_CFG),
Is it because the Ext. Tag(0xA0 0x0D) can't be identified?
Is there anything need to be take card if we create more NXP_RF_CONF_BLK_x? 

/////////////////////////////////////////////////////////////////////////////////
01-06 22:14:59.507  1021  8909 D NxpNciX : len = 166 > 2002A313A00D0604359001F401A00D06064401900300A00D060630B0011000A00D0606420200FFFFA00D03063F04A00D0620428800FFFFA00D0422442200A00D06222D50340C00A00D063242F800FFFFA00D06342D24370C00A00D06343386800070A00D0434442200A00D06422D15450D00A00D0446442200A00D06462D05590E00A00D0644428800FFFFA00D06562D059F0C00A00D0654428800FFFFA00D060A3380860070
01-06 22:14:59.507  1021  8909 D NxpTml  : PN54X - I2C Write successful.....
01-06 22:14:59.507  1021  8909 D NxpTml  : PN54X - Posting Fresh Write message.....
01-06 22:14:59.507  1021  8909 D NxpTml  : PN54X - Tml Writer Thread Running................
01-06 22:14:59.507  1021  8911 D NxpHal  : write successful status = 0x0
01-06 22:14:59.507  1021  8906 D NxpHal  : Response timer started
01-06 22:14:59.507  1021  8906 D NxpHal  : Waiting after ext cmd sent
01-06 22:14:59.548  1021  8908 D NxpTml  : PN54X - I2C Read successful.....
01-06 22:14:59.549  1021  8908 D NxpNciR : len =  11 > 4002080903A00DA00DA00D
01-06 22:14:59.549  1021  8908 D NxpTml  : PN54X - Posting read message.....
01-06 22:14:59.549  1021  8911 D NxpHal  : read successful status = 0x0
01-06 22:14:59.549  1021  8911 D NxpHal  : phNxpNciHal_print_res_status: response status =STATUS_INVALID_PARAM
/////////////////////////////////////////////////////////////////////////////////

Regards,
Daniel

**Comment by jgeslin** [comment]
Hi,

The issue seems to be the same faced by some others for which a fix was provided: https://github.com/NXPNFCLinux/linux_libnfc-nci/commit/9b774ef656c22c4a14018c8916691bd708c95de5#diff-fca6cf6d5c39d91a1ec38e30f4956fa8.
Related issue: https://github.com/NXPNFCLinux/linux_libnfc-nci/issues/59.

Unfortunately when the sample gets corrupted there is no way to recover. The only possibility is to replace the sample.

Regards,
Jeremy.

**Comment by Danielchiu73** [comment]
Hi Jeremy,

You mean the I2C fragmentation will not impact the Ext. Tag(0xA0 0x0D)  for the  NXP_RF_CONF_BLK_1 setting,right?

below is the ADB log:
[aplog_TOMBSTONE_20000106222509.log](https://github.com/NXPNFCLinux/nxpnfc_android_marshmallow/files/1496285/aplog_TOMBSTONE_20000106222509.log)

01-06 22:21:02.285  1021  9053 D NxpNciX : len = 166 > 2002A313A00D0604359001F401A00D06064401900300A00D060630B0011000A00D0606420200FFFFA00D03063F04A00D0620428800FFFFA00D0422442200A00D06222D50340C00A00D063242F800FFFFA00D06342D24370C00A00D06343386800070A00D0434442200A00D06422D15450D00A00D0446442200A00D06462D05590E00A00D0644428800FFFFA00D06562D059F0C00A00D0654428800FFFFA00D060A3380860070
01-06 22:21:02.326  1021  9052 D NxpNciR : len =  11 > 4002080903A00DA00DA00D
01-06 22:21:02.327  1021  9055 D NxpHal  : phNxpNciHal_print_res_status: response status =STATUS_INVALID_PARAM

We can also see the Polling Loop Started message. 
01-06 22:21:05.885  1021  9050 D NxpHal  : > Polling Loop Started

BTW,
Do you know what is message below?
01-06 22:25:07.683  1021  9163 E BrcmNfcNfa: GKI_getbuf() unable to allocate buffer!!!!!

Thank you,
Daniel

**Comment by jgeslin** [comment]
This is not related to fragmentation. From my side I am able to run this 166 bytes length command via 32 bytes packets. You can anyway remove the NXP_RF_CONF_BLK_1 section from the libnfc-nxp.conf file to test, but to my mind it may fail later when starting the discovery loop.
You can also split this command into several NXP_RF_CONF_BLK_x blocks like below, but it should failed at some point anyway:
```
NXP_RF_CONF_BLK_1={20, 02, 1C, 03,
    A0, 0D, 06, 04, 35, 90, 01, F4, 01, 
    A0, 0D, 06, 06, 44, 01, 90, 03, 00, 
    A0, 0D, 06, 06, 30, B0, 01, 10, 00
}
NXP_RF_CONF_BLK_2={20, 02, 1C, 03,
    A0, 0D, 06, 06, 42, 02, 00, FF, FF,
    A0, 0D, 06, 22, 2D, 50, 34, 0C, 00,
    A0, 0D, 06, 20, 42, 88, 00, FF, FF
}
NXP_RF_CONF_BLK_3={20, 02, 1C, 04,
    A0, 0D, 03, 06, 3F, 04,
    A0, 0D, 04, 22, 44, 22, 00,
    A0, 0D, 04, 34, 44, 22, 00,
    A0, 0D, 04, 46, 44, 22, 00
}
NXP_RF_CONF_BLK_4={20, 02, 1C, 03,
    A0, 0D, 06, 34, 2D, 24, 37, 0C, 00,
    A0, 0D, 06, 34, 33, 86, 80, 00, 70,
    A0, 0D, 06, 32, 42, F8, 00, FF, FF
}
NXP_RF_CONF_BLK_5={20, 02, 1C, 03,
    A0, 0D, 06, 42, 2D, 15, 45, 0D, 00,
    A0, 0D, 06, 46, 2D, 05, 59, 0E, 00,
    A0, 0D, 06, 44, 42, 88, 00, FF, FF
}
NXP_RF_CONF_BLK_6={20, 02, 1C, 03,
    A0, 0D, 06, 56, 2D, 05, 9F, 0C, 00,
    A0, 0D, 06, 54, 42, 88, 00, FF, FF,
    A0, 0D, 06, 0A, 33, 80, 86, 00, 70
}
```

**Comment by Danielchiu73** [comment]
Hi Jeremy,

OK.

BTW,
Can you explain more about it should failed if we split the command into several NXP_RF_CONF_BLK_x?Thanks.

Regards,
Daniel

**Comment by jgeslin** [comment]
From my mind the issue face is the EEPROM corruption. If it is the case, splitting the command to set those parameters won't help because the writing will always fail whatever the length of the command (this operation being independent from the fragmentation mechanism).

**Comment by Danielchiu73** [comment]
Hi Jeremy,

Customer had used another PCBA to review the NFCC initialization and there is no issue like EEPROM corruption. so they have no any support need.
Thank you very much for your support.

Regards,
Daniel
